# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 13:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nickname', models.CharField(max_length=10)),
                ('College', models.CharField(max_length=20)),
                ('Sex', models.NullBooleanField()),
                ('Signature', models.CharField(max_length=100, null=True)),
                ('Fb_sum', models.IntegerField(default=0)),
                ('Hf_sum', models.IntegerField(default=0)),
                ('Gz_sum', models.IntegerField(default=0)),
                ('Bgz_sum', models.IntegerField(default=0)),
                ('Sc_sum', models.IntegerField(default=0)),
                ('Rank', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
